comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: no
  require_head: yes
  branches: null

coverage:
  status:
    project:
      default: false
      app:
        target: 80%
        paths: "graphene_permissions/"