comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: no
  require_head: yes
  branches: null

coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        paths: "tests/"  # only include coverage in "tests/" folder
      app:  # declare a new status context "app"
        paths: "!tests/"  # remove all files in "tests/"